"""Compatibility facade for pure domain exit-plan evaluation."""

from __future__ import annotations

from trader.domain.planning.exit_engine import (
    ExitEvaluation,
    ExitSignal,
    ProfitProtection,
    Side,
    TakeProfit,
    TradePlan,
    _best_favorable_move,
    _breakeven_stop,
    _check_stop,
    _check_tp,
    _check_trailing,
    _close,
    _exit_side,
    _favorable_move,
    _lock_r_stop,
    _max_hold_due,
    _min_hold_elapsed,
    _next_take_profit,
    _profit_protection_signal,
    _risk_per_share,
    _signal,
    _trail_amount,
    _trailing_enabled,
    _update_watermarks,
    evaluate_plan,
)

__all__ = [
    "ExitEvaluation",
    "ExitSignal",
    "ProfitProtection",
    "Side",
    "TakeProfit",
    "TradePlan",
    "_best_favorable_move",
    "_breakeven_stop",
    "_check_stop",
    "_check_tp",
    "_check_trailing",
    "_close",
    "_exit_side",
    "_favorable_move",
    "_lock_r_stop",
    "_max_hold_due",
    "_min_hold_elapsed",
    "_next_take_profit",
    "_profit_protection_signal",
    "_risk_per_share",
    "_signal",
    "_trail_amount",
    "_trailing_enabled",
    "_update_watermarks",
    "evaluate_plan",
]
