"""Compatibility facade for pure domain indicator-watch policy."""

from __future__ import annotations

from trader.domain.planning.indicator_watch import (
    ARMED_ORDER_MAX_TTL_MINUTES,
    DEFAULT_INDICATORS,
    DEFAULT_WATCH_TTL_MINUTES,
    FAMILIES,
    INDICATOR_LABEL_VALUES,
    IndicatorWatchResult,
    WATCH_REJECT_INVALID_ARMED_ORDER,
    WATCH_REJECT_INVALID_OPERATOR,
    WATCH_REJECT_MISSING_THRESHOLD,
    WATCH_REJECT_NON_FINITE_THRESHOLD,
    WATCH_REJECT_NOT_MAPPING,
    WATCH_REJECT_NO_CONDITIONS,
    WATCH_REJECT_UNKNOWN_INDICATOR,
    WATCH_REJECT_UNKNOWN_LABEL,
    WATCH_SUMMARY_RATIONALE_MAX_LENGTH,
    WATCH_VALID_OPERATORS,
    armed_order_price_coherent,
    build_indicator_watch,
    evaluate_indicator_watches,
    family_for_symbol,
    is_armed_plan,
    label_to_value,
    normalize_armed_order,
    normalize_indicator_watch,
    normalize_temporal_query,
    summarize_watch,
    watch_market_requests,
)

__all__ = [
    "ARMED_ORDER_MAX_TTL_MINUTES",
    "DEFAULT_INDICATORS",
    "DEFAULT_WATCH_TTL_MINUTES",
    "FAMILIES",
    "INDICATOR_LABEL_VALUES",
    "IndicatorWatchResult",
    "WATCH_REJECT_INVALID_ARMED_ORDER",
    "WATCH_REJECT_INVALID_OPERATOR",
    "WATCH_REJECT_MISSING_THRESHOLD",
    "WATCH_REJECT_NON_FINITE_THRESHOLD",
    "WATCH_REJECT_NOT_MAPPING",
    "WATCH_REJECT_NO_CONDITIONS",
    "WATCH_REJECT_UNKNOWN_INDICATOR",
    "WATCH_REJECT_UNKNOWN_LABEL",
    "WATCH_SUMMARY_RATIONALE_MAX_LENGTH",
    "WATCH_VALID_OPERATORS",
    "armed_order_price_coherent",
    "build_indicator_watch",
    "evaluate_indicator_watches",
    "family_for_symbol",
    "is_armed_plan",
    "label_to_value",
    "normalize_armed_order",
    "normalize_indicator_watch",
    "normalize_temporal_query",
    "summarize_watch",
    "watch_market_requests",
]
