"""Protocols for planning-facing stores."""

from __future__ import annotations

from typing import Protocol

from trader.domain.trade_plan import TradePlan


class TradePlanStoreLike(Protocol):
    def open_plans(self) -> list[TradePlan]: ...
    def upsert(self, plan: TradePlan) -> None: ...
    def close(self, plan_id: str) -> None: ...
    def close_symbol(self, symbol: str) -> None: ...
    def sync_symbol_quantity(self, symbol: str, remaining_quantity: float) -> None: ...
