"""Compatibility facade for pure domain relevance gating."""

from __future__ import annotations

from trader.domain.planning.relevance_gate import (
    CALM_REVIEW_MAX_HOURS,
    FRESH_AFTER_STALE_REASON,
    FRESH_PROBE_INTERVAL_MINUTES,
    FRESH_PROBE_WAKE_FINGERPRINT_KEY,
    HOT_REVIEW_MAX_HOURS,
    HOT_REVIEW_WAKE_FINGERPRINT_KEY,
    HOT_SETUP_REASON,
    POSITION_REVIEW_DEBOUNCE_HOURS,
    REVIEWED_BAR_FINGERPRINT_KEY,
    REVIEWED_TRIGGER_FINGERPRINT_KEY,
    SAME_RUNTIME_BAR_REASON,
    SIGNAL_DEBOUNCE_HOURS,
    STALE_REVIEW_FINGERPRINT_KEY,
    STALE_REVIEW_PENDING,
    STALE_REPLAY_WAIT_REASON,
    THESIS_INTERVALS,
    TRIGGER_INTERVAL,
    _HTF_SIG_PREFIXES,
    _as_wake_reason_set,
    _cockpit_cell,
    _debounced,
    _has_htf_sig,
    _htf_material,
    _signal_fingerprint,
    cockpit_activity,
    execution_is_enabled,
    is_pending_stale_review,
    persistent_wake_fingerprints,
    persistent_wake_reasons,
    reviewed_bar_fingerprint,
    reviewed_trigger_fingerprint,
    session_is_open,
    should_mark_stale_review_pending,
    symbol_needs_llm,
)


__all__ = [
    "CALM_REVIEW_MAX_HOURS",
    "FRESH_AFTER_STALE_REASON",
    "FRESH_PROBE_INTERVAL_MINUTES",
    "FRESH_PROBE_WAKE_FINGERPRINT_KEY",
    "HOT_REVIEW_MAX_HOURS",
    "HOT_REVIEW_WAKE_FINGERPRINT_KEY",
    "HOT_SETUP_REASON",
    "POSITION_REVIEW_DEBOUNCE_HOURS",
    "REVIEWED_BAR_FINGERPRINT_KEY",
    "REVIEWED_TRIGGER_FINGERPRINT_KEY",
    "SAME_RUNTIME_BAR_REASON",
    "SIGNAL_DEBOUNCE_HOURS",
    "STALE_REVIEW_FINGERPRINT_KEY",
    "STALE_REVIEW_PENDING",
    "STALE_REPLAY_WAIT_REASON",
    "THESIS_INTERVALS",
    "TRIGGER_INTERVAL",
    "_HTF_SIG_PREFIXES",
    "_as_wake_reason_set",
    "_cockpit_cell",
    "_debounced",
    "_has_htf_sig",
    "_htf_material",
    "_signal_fingerprint",
    "cockpit_activity",
    "execution_is_enabled",
    "is_pending_stale_review",
    "persistent_wake_fingerprints",
    "persistent_wake_reasons",
    "reviewed_bar_fingerprint",
    "reviewed_trigger_fingerprint",
    "session_is_open",
    "should_mark_stale_review_pending",
    "symbol_needs_llm",
]
