2301.TW: Lite-On Technology Corporation
2303.TW: United Microelectronics Corporation
2308.TW: Delta Electronics, Inc.
2317.TW: Hon Hai Precision Industry Co., Ltd.
2327.TW: Yageo Corporation
2330.TW: Taiwan Semiconductor Manufacturing Company Limited
2368.TW: Gold Circuit Electronics Ltd.
2379.TW: Realtek Semiconductor Corp.
2382.TW: Quanta Computer Inc.
2383.TW: Elite Material Co., Ltd.
2404.TW: United Integrated Services Co., Ltd.
2408.TW: Nanya Technology Corporation
2449.TW: King Yuan Electronics Co., Ltd.
2454.TW: MediaTek Inc.
2492.TW: Walsin Technology Corporation
3017.TW: Asia Vital Components Co., Ltd.
3037.TW: Unimicron Technology Corp.
3081.TWO: LandMark Optoelectronics Corporation
3131.TWO: Grand Process Technology Corporation
3189.TW: Kinsus Interconnect Technology Corp.
3231.TW: Wistron Corporation
3324.TWO: Auras Technology Co., Ltd.
3443.TW: Global Unichip Corp.
3532.TW: Formosa Sumco Technology Corporation
3661.TW: Alchip Technologies, Limited
3711.TW: ASE Technology Holding Co., Ltd.
6442.TW: EZconn Corporation
6488.TWO: GlobalWafers Co., Ltd.
8046.TW: Nan Ya Printed Circuit Board Corporation
8299.TWO: Phison Electronics Corp.
A2A.MI: A2A S.p.A.
ABBN.SW: ABB Ltd
ABBV: AbbVie Inc.
ABT: Abbott Laboratories
ACA.PA: Crédit Agricole S.A.
ADBE: Adobe Inc.
AEP: American Electric Power Company, Inc.
AI.PA: L'Air Liquide S.A.
AIR.PA: Airbus SE
AKE.PA: Arkema S.A.
ALB: Albemarle Corporation
ALV.DE: Allianz SE
AM.PA: Dassault Aviation société anonyme
AMAT: Applied Materials, Inc.
AMD: Advanced Micro Devices, Inc.
AMGN: Amgen Inc.
AMS.MC: Amadeus IT Group, S.A.
AMT: American Tower Corporation
AMZN: Amazon.com, Inc.
AON: Aon plc
APD: Air Products and Chemicals, Inc.
ASML.AS: ASML Holding N.V.
AVB: AvalonBay Communities, Inc.
AVGO: Broadcom Inc.
AWK: American Water Works Company, Inc.
AXP: American Express Company
AZN.L: AstraZeneca PLC
BA: The Boeing Company
BAC: Bank of America Corporation
BAS.DE: BASF SE
BKNG: Booking Holdings Inc.
BKR: Baker Hughes Company
BLK: BlackRock, Inc.
BMW.DE: Bayerische Motoren Werke Aktiengesellschaft
BMY: Bristol-Myers Squibb Company
BN.PA: Danone S.A.
BNP.PA: BNP Paribas SA
BP.L: BP p.l.c.
BRBY.L: Burberry Group plc
C: Citigroup Inc.
CAP.PA: Capgemini SE
CARL-B.CO: Carlsberg A/S
CAT: Caterpillar Inc.
CB: Chubb Limited
CF: CF Industries Holdings, Inc.
CFR.SW: Compagnie Financière Richemont SA
CHTR: Charter Communications, Inc.
CL: Colgate-Palmolive Company
CMCSA: Comcast Corporation
COF: Capital One Financial Corporation
COLO-B.CO: Coloplast A/S
COP: ConocoPhillips
COST: Costco Wholesale Corporation
CRH: CRH plc
CRM: Salesforce, Inc.
CS.PA: AXA SA
CSX: CSX Corporation
CVS: CVS Health Corporation
CVX: Chevron Corporation
D: Dominion Energy, Inc.
DBK.DE: Deutsche Bank Aktiengesellschaft
DD: DuPont de Nemours, Inc.
DE: Deere & Company
DGE.L: Diageo plc
DHR: Danaher Corporation
DIS: The Walt Disney Company
DLR: Digital Realty Trust, Inc.
DOW: Dow Inc.
DSY.PA: Dassault Systèmes SE
DTE.DE: Deutsche Telekom AG
DUK: Duke Energy Corporation
DVN: Devon Energy Corporation
EA: Electronic Arts Inc.
ECL: Ecolab Inc.
EDP.LS: EDP, S.A.
EMR: Emerson Electric Co.
ENEL.MI: Enel SpA
ENGI.PA: Engie SA
ENI.MI: Eni S.p.A.
EOAN.DE: E.ON SE
EOG: EOG Resources, Inc.
EQIX: Equinix, Inc.
EQNR.OL: Equinor ASA
EQR: Equity Residential
ERIC-B.ST: Telefonaktiebolaget LM Ericsson (publ)
ES: Eversource Energy
ESSITY-B.ST: Essity AB (publ)
ETN: Eaton Corporation plc
EXC: Exelon Corporation
EXR: Extra Space Storage Inc.
F: Ford Motor Company
FCX: Freeport-McMoRan Inc.
FDX: FedEx Corporation
FORTUM.HE: Fortum Oyj
FOXA: Fox Corporation
FRE.DE: Fresenius SE & Co. KGaA
GALP.LS: Galp Energia, SGPS, S.A.
GD: General Dynamics Corporation
GE: GE Aerospace
GIS: General Mills, Inc.
GLE.PA: Société Générale Société anonyme
GM: General Motors Company
GOOGL: Alphabet Inc.
GS: The Goldman Sachs Group, Inc.
GSK.L: GSK plc
HAL: Halliburton Company
HCA: HCA Healthcare, Inc.
HD: The Home Depot, Inc.
HEXA-B.ST: Hexagon AB (publ)
HO.PA: Thales S.A.
HOLN.SW: Holcim AG
HON: Honeywell International Inc.
HSY: The Hershey Company
IBE.MC: Iberdrola, S.A.
IFX.DE: Infineon Technologies AG
INGA.AS: ING Groep N.V.
INTC: Intel Corporation
INTU: Intuit Inc.
ISRG: Intuitive Surgical, Inc.
JNJ: Johnson & Johnson
JPM: JPMorgan Chase & Co.
KER.PA: Kering SA
KHC: The Kraft Heinz Company
KNEBV.HE: KONE Oyj
KO: The Coca-Cola Company
KPN.AS: Koninklijke KPN N.V.
LIN: Linde plc
LIN.DE: Linde plc
LLY: Eli Lilly and Company
LMT: Lockheed Martin Corporation
LOW: Lowe's Companies, Inc.
MAR: Marriott International, Inc.
MBG.DE: Mercedes-Benz Group AG
MC.PA: LVMH Moët Hennessy - Louis Vuitton, Société Européenne
MCD: McDonald's Corporation
MDT: Medtronic plc
META: Meta Platforms, Inc.
MMM: 3M Company
MO: Altria Group, Inc.
MONC.MI: Moncler S.p.A.
MOS: The Mosaic Company
MPC: Marathon Petroleum Corporation
MRK: Merck & Co., Inc.
MRSH: Marsh & McLennan Companies, Inc.
MS: Morgan Stanley
MSFT: Microsoft Corporation
MT.AS: ArcelorMittal S.A.
MU: Micron Technology, Inc.
MUV2.DE: Münchener Rückversicherungs-Gesellschaft Aktiengesellschaft in München
NEE: NextEra Energy, Inc.
NEM: Newmont Corporation
NESN.SW: Nestlé S.A.
NESTE.HE: Neste Oyj
NFLX: Netflix, Inc.
NKE: NIKE, Inc.
NN.AS: NN Group N.V.
NOC: Northrop Grumman Corporation
NOKIA.HE: Nokia Oyj
NOVN.SW: Novartis AG
NOVO-B.CO: Novo Nordisk A/S
NOW: ServiceNow, Inc.
NVDA: NVIDIA Corporation
NXPI: NXP Semiconductors N.V.
O: Realty Income Corporation
OMV.VI: OMV Aktiengesellschaft
OR.PA: L'Oréal S.A.
ORA.PA: Orange S.A.
ORCL: Oracle Corporation
OXY: Occidental Petroleum Corporation
PCG: PG&E Corporation
PEP: PepsiCo, Inc.
PFE: Pfizer Inc.
PG: The Procter & Gamble Company
PGR: The Progressive Corporation
PHIA.AS: Koninklijke Philips N.V.
PLD: Prologis, Inc.
PM: Philip Morris International Inc.
PPG: PPG Industries, Inc.
PROX.BR: Proximus PLC
PSA: Public Storage
PSKY: Paramount Skydance Corporation
PSX: Phillips 66
QCOM: QUALCOMM Incorporated
QQQ: Invesco QQQ Trust
RED.MC: Redeia Corporación, S.A.
REP.MC: Repsol, S.A.
RHM.DE: Rheinmetall AG
RMS.PA: Hermès International Société en commandite par actions
RO.SW: Roche Holding AG
ROST: Ross Stores, Inc.
RR.L: Rolls-Royce Holdings plc
RTX: RTX Corporation
RWE.DE: RWE Aktiengesellschaft
SAF.PA: Safran SA
SAN.MC: Banco Santander, S.A.
SAN.PA: Sanofi
SAP.DE: SAP SE
SBUX: Starbucks Corporation
SCHW: The Charles Schwab Corporation
SHELL.AS: Shell plc
SHW: The Sherwin-Williams Company
SIE.DE: Siemens Aktiengesellschaft
SLB: SLB N.V.
SO: The Southern Company
SOLB.BR: Solvay SA
SPG: Simon Property Group, Inc.
SPY: State Street SPDR S&P 500 ETF Trust
SRE: Sempra
STLA: Stellantis N.V.
STMN.SW: Straumann Holding AG
STMPA.PA: STMicroelectronics N.V.
SU.PA: Schneider Electric S.E.
SY1.DE: Symrise AG
SYY: Sysco Corporation
T: AT&T Inc.
TEF.MC: Telefónica, S.A.
TEL2-B.ST: Tele2 AB (publ)
TELIA.ST: Telia Company AB (publ)
TGT: Target Corporation
TIT.MI: Telecom Italia S.p.A.
TJX: The TJX Companies, Inc.
TMO: Thermo Fisher Scientific Inc.
TMUS: T-Mobile US, Inc.
TSLA: Tesla, Inc.
TTE.PA: TotalEnergies SE
TTWO: Take-Two Interactive Software, Inc.
TXN: Texas Instruments Incorporated
UCB.BR: UCB SA
UCG.MI: UniCredit S.p.A.
UMI.BR: Umicore SA
UNA.AS: Unilever PLC
UNH: UnitedHealth Group Incorporated
UPS: United Parcel Service, Inc.
USB: U.S. Bancorp
VIE.PA: Veolia Environnement SA
VLO: Valero Energy Corporation
VOD.L: Vodafone Group Public Limited Company
VOLV-B.ST: AB Volvo (publ)
VOW3.DE: Volkswagen AG
VTR: Ventas, Inc.
VZ: Verizon Communications Inc.
WBD: Warner Bros. Discovery, Inc.
WEC: WEC Energy Group, Inc.
WELL: Welltower Inc.
WFC: Wells Fargo & Company
WKL.AS: Wolters Kluwer N.V.
WMT: Walmart Inc.
XEL: Xcel Energy Inc.
XOM: Exxon Mobil Corporation
YAR.OL: Yara International ASA
YUM: Yum! Brands, Inc.
ZURN.SW: Zurich Insurance Group AG
^FCHI: CAC 40
