symbols:
- 2886.TW
- 2892.TW
- BN.PA
- CFR.SW
- ECL
- GE
- NOVN.SW
- NOVO-B.CO
- PH
- RR.L
- SGRO.L
- STMN.SW
- TIT.MI
- UBSG.SW
- UPM.HE
- USB
- WELL
- WMB
- AXP
- SYY
- CMS
- COF
- BAC
- AMCR
- TRV
- AEE
- TGT
- DHI
- CVS
- SBUX
- GIS
- TTWO
- PGR
- KVUE
- HON
- AMAT
