symbols:
- BMY
- C
- TIT.MI
- ASML.AS
- UBSG.SW
- IBE.MC
- EBS.VI
- GLE.PA
- CFR.SW
- SAN.MC
- BNP.PA
- BMW.DE
- ACA.PA
- DBK.DE
- ATCO-A.ST
- SOLB.BR
- COLO-B.CO
- PROX.BR
- SAF.PA
- KPN.AS
- RMS.PA
- ENEL.MI
- SSAB-A.ST
- STMN.SW
- KBC.BR
- UCG.MI
- ALV.DE
