"""Ports for planning-facing collaborators."""

from __future__ import annotations

from datetime import datetime
from typing import Iterable
from typing import Protocol

from trader.domain.trade_plan import TradePlan


class TradePlanStoreLike(Protocol):
    def open_plans(self) -> list[TradePlan]: ...
    def upsert(self, plan: TradePlan) -> None: ...
    def close(self, plan_id: str) -> None: ...
    def close_symbol(self, symbol: str) -> None: ...
    def sync_symbol_quantity(self, symbol: str, remaining_quantity: float) -> None: ...


class SchedulerLike(Protocol):
    def next_wake(self, symbol: str | None = None) -> datetime | None: ...
    def set_next_wake_in(self, *, minutes: float, now: datetime | None = None) -> str: ...
    def set_symbol_next_wake(self, symbol: str, when_iso: str) -> None: ...
    def clear_symbol_next_wake(self, symbol: str) -> None: ...
    def set_symbol_next_wake_in(
        self,
        symbol: str,
        *,
        minutes: float,
        now: datetime | None = None,
    ) -> str: ...
    def due_symbols(self, symbols: Iterable[str], now: datetime | None = None) -> list[str]: ...
    def seconds_until_wake(
        self,
        symbols: Iterable[str] | None = None,
        now: datetime | None = None,
    ) -> float: ...
    def set_symbol_indicator_watch(self, symbol: str, watch: dict) -> None: ...
    def active_indicator_watches(self, now: datetime | None = None) -> list[dict]: ...
    def pop_expired_indicator_watches(self, now: datetime | None = None) -> list[dict]: ...
    def remove_indicator_watch(self, watch_id: str) -> None: ...
    def reconcile_universe(self, symbols: Iterable[str]) -> None: ...
    def get_stale_streak(self, symbol: str) -> int: ...
    def set_stale_streak(self, symbol: str, streak: int) -> None: ...
    def reset_stale_streak(self, symbol: str) -> None: ...
