"""agent_tools — validation, budgets, handlers lecture-seule (design 2026-06-29)."""
from __future__ import annotations

from trader.agent_tools import core as core
from trader.agent_tools.core import (
    OUTCOME_BUDGET_EXHAUSTED,
    OUTCOME_ERROR,
    OUTCOME_OK,
    OUTCOME_REJECTED,
    OUTCOME_TRUNCATED,
    _MAX_RAW_CALLS,
    _SCRUB_DEPTH,
    _SCRUB_DICT_KEYS,
    _SCRUB_ID_LEN,
    _SCRUB_LIST_LEN,
    _SCRUB_STR_LEN,
    _budget_exhausted,
    _rejected,
    _scrub_args,
    _scrub_str,
    _symbols_mentioned,
    AgentToolCall,
    AgentToolResult,
    AgentToolTrace,
    IndicatorResolver,
    JsonObject,
    LearningsRecallProvider,
    PositionRiskProvider,
    RecentDecisionsProvider,
    ToolContext,
    ToolArgs,
    ToolOutcome,
    ToolPayload,
    ToolRoundLimits,
    ToolSpec,
    calls_for_symbol,
    execute_tool_call,
    execute_tool_round,
    results_prompt_payload,
    round_runtime_payload,
    validate_tool_call,
)
from trader.agent_tools import registry as registry
from trader.agent_tools.attribution import (
    _ATTRIBUTION_SCOPES,
    _MAX_DECISION_ROWS,
    _handle_get_attribution,
    _handle_get_recent_decisions,
    _validate_get_attribution,
    _validate_get_recent_decisions,
)
from trader.agent_tools.freshness import (
    _MAX_FRESHNESS_SYMBOLS,
    _handle_get_freshness,
    _validate_get_freshness,
)
from trader.agent_tools.indicators import (
    _MAX_INDICATOR_MATCHES,
    _MAX_INDICATORS_PER_CALL,
    _handle_describe_data,
    _handle_find_indicators,
    _handle_get_indicator_context,
    _validate_find_indicators,
    _validate_get_indicator_context,
)
from trader.agent_tools.learnings import (
    _MAX_RECALL_ROWS,
    _handle_recall_learnings,
    _validate_recall_learnings,
)
from trader.agent_tools.plans import (
    _MAX_PLAN_ROWS,
    _handle_get_active_plans,
    _validate_get_active_plans,
)
from trader.agent_tools.registry import TOOL_REGISTRY
from trader.agent_tools.risk import (
    _handle_get_position_risk,
    _validate_symbol_only,
)

__all__ = [
    "OUTCOME_BUDGET_EXHAUSTED",
    "OUTCOME_ERROR",
    "OUTCOME_OK",
    "OUTCOME_REJECTED",
    "OUTCOME_TRUNCATED",
    "TOOL_REGISTRY",
    "AgentToolCall",
    "AgentToolResult",
    "AgentToolTrace",
    "IndicatorResolver",
    "JsonObject",
    "LearningsRecallProvider",
    "PositionRiskProvider",
    "RecentDecisionsProvider",
    "ToolArgs",
    "ToolContext",
    "ToolOutcome",
    "ToolPayload",
    "ToolRoundLimits",
    "ToolSpec",
    "calls_for_symbol",
    "core",
    "execute_tool_call",
    "execute_tool_round",
    "registry",
    "results_prompt_payload",
    "round_runtime_payload",
    "validate_tool_call",
    "_ATTRIBUTION_SCOPES",
    "_MAX_DECISION_ROWS",
    "_MAX_FRESHNESS_SYMBOLS",
    "_MAX_INDICATOR_MATCHES",
    "_MAX_INDICATORS_PER_CALL",
    "_MAX_PLAN_ROWS",
    "_MAX_RAW_CALLS",
    "_MAX_RECALL_ROWS",
    "_SCRUB_DEPTH",
    "_SCRUB_DICT_KEYS",
    "_SCRUB_ID_LEN",
    "_SCRUB_LIST_LEN",
    "_SCRUB_STR_LEN",
    "_budget_exhausted",
    "_handle_describe_data",
    "_handle_find_indicators",
    "_handle_get_active_plans",
    "_handle_get_attribution",
    "_handle_get_freshness",
    "_handle_get_indicator_context",
    "_handle_get_position_risk",
    "_handle_get_recent_decisions",
    "_handle_recall_learnings",
    "_rejected",
    "_scrub_args",
    "_scrub_str",
    "_symbols_mentioned",
    "_validate_find_indicators",
    "_validate_get_active_plans",
    "_validate_get_attribution",
    "_validate_get_freshness",
    "_validate_get_indicator_context",
    "_validate_get_recent_decisions",
    "_validate_recall_learnings",
    "_validate_symbol_only",
]
